rvm:
  - 2.2.9
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - ruby-head

addons:
  firefox: latest

# whitelist
branches:
  only:
    - master

gemfile:
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_4_1.gemfile
  - gemfiles/rails_4_0.gemfile

matrix:
  fast_finish: true
  exclude:
    - rvm: 2.4.4
      gemfile: gemfiles/rails_4_0.gemfile
    - rvm: 2.4.4
      gemfile: gemfiles/rails_4_1.gemfile
    - rvm: 2.5.1
      gemfile: gemfiles/rails_4_0.gemfile
    - rvm: 2.5.1
      gemfile: gemfiles/rails_4_1.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_4_0.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_4_1.gemfile
  allow_failures:
    - rvm: ruby-head

before_install: gem update --remote bundler
before_script: geckodriver -V
