name: Release to RubyGems

on:
  push:
    branches:
      - release/*

jobs:
  pre-release-check:
    uses: cucumber/.github/.github/workflows/prerelease-checks.yml@main
  
  test:
    uses: ./.github/workflows/test.yml

  publish-rubygem:
    name: Publish Ruby Gem
    needs: [pre-release-check, test]
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: cucumber/action-publish-rubygem@d8918cbdee789cfc78f346a96a59596b87795be1 # v1.0.0
        with:
          rubygems_api_key: ${{ secrets.RUBYGEMS_API_KEY }}

  create-github-release:
    name: Create GitHub Release and Git tag
    needs: publish-rubygem
    runs-on: ubuntu-latest
    environment: Release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: cucumber/action-create-github-release@cf2c6f77ba35d2424362e83393a1c4c004cf2ddb # v1.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
